openapi: 3.0.0
info:
  title: API Catways
  version: 1.0.0
  description: Documentation de l’API port Russell

servers:
  - url: http://localhost:3000

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    User:
      type: object
      properties:
        _id: { type: string }
        username: { type: string }
        email: { type: string }
    Catway:
      type: object
      properties:
        catwayNumber: { type: integer }
        catwayType: { type: string }
        catwayState: { type: string }
    Reservation:
      type: object
      properties:
        _id: { type: string }
        catwayNumber: { type: integer }
        startDate: { type: string, format: date }
        endDate: { type: string, format: date }
        boatName: { type: string }
        fullName: { type: string }
        status: { type: string }

security:
  - bearerAuth: []

paths:
  /users/login:
    post:
      summary: Authentification utilisateur
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email: { type: string }
                password: { type: string }
      responses:
        '200':
          description: Token JWT
          content:
            application/json:
              schema:
                type: object
                properties:
                  token: { type: string }

  /users/add:
    post:
      summary: Inscription utilisateur
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username: { type: string }
                email: { type: string }
                password: { type: string }
      responses:
        '201':
          description: Utilisateur créé

  /users/me:
    get:
      summary: Infos utilisateur connecté
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Infos utilisateur
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
    patch:
      summary: Modifier le profil
      security:
        - bearerAuth: []
      requestBody:
        required: false
        content:
          application/json:
            schema:
              type: object
              properties:
                username: { type: string }
                email: { type: string }
                password: { type: string }
      responses:
        '200':
          description: Profil mis à jour
    delete:
      summary: Supprimer le compte
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Compte supprimé

  /catways:
    get:
      summary: Liste des catways
      responses:
        '200':
          description: Liste des catways
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Catway'
    post:
      summary: Ajouter un catway
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Catway'
      responses:
        '201':
          description: Catway créé

  /catways/{catwayNumber}:
    patch:
      summary: Modifier un catway
      parameters:
        - in: path
          name: catwayNumber
          required: true
          schema: { type: integer }
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                catwayState: { type: string }
      responses:
        '200':
          description: Catway modifié
    delete:
      summary: Supprimer un catway
      parameters:
        - in: path
          name: catwayNumber
          required: true
          schema: { type: integer }
      responses:
        '200':
          description: Catway supprimé

  /catways/reserve:
    post:
      summary: Réserver un catway
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                catwayNumber: { type: integer }
                startDate: { type: string, format: date }
                endDate: { type: string, format: date }
                boatName: { type: string }
                fullName: { type: string }
      responses:
        '201':
          description: Réservation créée

  /reservations/me:
    get:
      summary: Liste des réservations de l'utilisateur
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Liste des réservations
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Reservation'

  /reservations/{id}:
    patch:
      summary: Modifier une réservation
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema: { type: string }
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                startDate: { type: string, format: date }
                endDate: { type: string, format: date }
                boatName: { type: string }
                fullName: { type: string }
      responses:
        '200':
          description: Réservation modifiée
    delete:
      summary: Supprimer une réservation
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema: { type: string }
      responses:
        '200':
          description: Réservation supprimée